### ISSUE TITLE
env file missing

### ISSUE THREAD

**Issue by BryanAlberts** [TheLegenDev/Nub-Bot#19]

**Comment by BryanAlberts** [comment]
also there no such called guildId in handleCommands.js only clientID
![image](https://github.com/TheLegenDev/Nub-Bot/assets/59321692/125603e4-a4a2-46e8-a460-9fa0bfccec70)

**Comment by loxt-nixo** [comment]
Create the .env File 🤦‍♀️

**Comment by BryanAlberts** [comment]
> Create the .env File 🤦‍♀️

i did, where is guildID

**Comment by BryanAlberts** [comment]
![image](https://github.com/TheLegenDev/Nub-Bot/assets/59321692/9879134a-a262-40d7-afcf-5b17d5da88b4)
my token are valid but still get the same error

**Comment by diptodeepb** [comment]
@SoundDr0ut You're advised to refer to previously closed issues before creating a new one. A similar issue has been addressed previously. However, I'll say this again ; the `.env` file hasn't been incorporated in the repository for obvious security reasons. We consider discord bot developers to be mindful enough, in order to create their own `.env` file and not require a template for doing the same.

**Comment by diptodeepb** [comment]
> also there no such called guildId in handleCommands.js only clientID ![image](https://private-user-images.githubusercontent.com/59321692/313426173-125603e4-a4a2-46e8-a460-9fa0bfccec70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODI0NzEsIm5iZiI6MTcxMTY4MjE3MSwicGF0aCI6Ii81OTMyMTY5Mi8zMTM0MjYxNzMtMTI1NjAzZTQtYTRhMi00NmU4LWE0NjAtOWZhMGJmY2NlYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDAzMTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTkyODI3ZWJhOTRhNTY5NmIzNjA0NzA1Zjg2ZjFjZTliMmExNzYxODNkZjY0YmQ2MDlmZTM1OGFmNzA5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f1gKbDbOUGATivoyT3pzRN1SlD4eDqAkXuQrf4hHBIw)

@SoundDr0ut You can easily define `guildId` yourself below the line where `clientId` has been defined. The reason we've not incorporated it ourselves is since it isn't required as this is a multi-guilded bot.

**Comment by diptodeepb** [comment]
No response received for 2 weeks. Assuming the issue has been addressed accurately and taken care of by the concerned user.
